cat > k8s/deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeapp-deployment
  labels:
    app: financeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financeapp
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
      - name: financeapp
        image: nikithamanvi/financeapp:latest
        ports:
        - containerPort: 8080
EOF
