apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeapp-deployment
  labels:
    app: financeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financeapp
  template:
    metadata:
      labels:
        app: financeapp
    spec:
      containers:
      - name: financeapp
        image: nikithamanvi/financeapp:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: financeapp-service
spec:
  selector:
    app: financeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort  # Change to LoadBalancer if using AWS EKS or other cloud providers
