cat > k8s/service.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
  name: financeapp-service
spec:
  type: NodePort
  selector:
    app: financeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
EOF
